export const pages = [
  { id: "heading", file: "01-heading.html", navLabel: "Forside", group: "Getting Started" },
  { id: "divider-1", file: "02-divider.html", navLabel: "01 Indledning", group: "Getting Started" },
  { id: "divider-2", file: "04-divider.html", isDivider: true },
  { id: "overview", file: "05-overview.html", navLabel: "02 Oversigt", group: "Getting Started" },
  { id: "divider-3", file: "06-divider.html", isDivider: true },
  { id: "content-where", file: "07-content-where.html", navLabel: "03 Content til Platform", group: "Getting Started" },
  { id: "divider-4", file: "08-divider.html", isDivider: true },
  { id: "audiences", file: "09-audiences.html", navLabel: "04 Målgrupper", group: "Getting Started" },
  { id: "divider-5", file: "10-divider.html", isDivider: true },
  { id: "styleguide", file: "11-styleguide.html", navLabel: "05 Visuel Identitet", group: "Brand" },
  { id: "divider-6", file: "12-divider.html", isDivider: true },
  { id: "facebook", file: "13-facebook-guidelines.html", navLabel: "06 Facebook", group: "Platform Guidelines" },
  { id: "divider-7", file: "14-divider.html", isDivider: true },
  { id: "instagram", file: "15-instagram-guidelines.html", navLabel: "07 Instagram", group: "Platform Guidelines" },
  { id: "divider-8", file: "16-divider.html", isDivider: true },
  { id: "linkedin", file: "17-linkedin-guidelines.html", navLabel: "08 LinkedIn", group: "Platform Guidelines" },
  { id: "divider-9", file: "18-divider.html", isDivider: true },
  { id: "tiktok", file: "19-tiktok-guidelines.html", navLabel: "09 TikTok", group: "Platform Guidelines" },
  { id: "divider-10", file: "20-divider.html", isDivider: true },
  { id: "catalogue", file: "21-catalogue-guidelines.html", navLabel: "10 Tone of Voice", group: "Process" },
  { id: "divider-11", file: "22-divider.html", isDivider: true },
  { id: "content-calendar", file: "23-content-calendar.html", navLabel: "11 Planlægning", group: "Process" },
  { id: "divider-12", file: "24-divider.html", isDivider: true },
  { id: "kpi", file: "25-kpi.html", navLabel: "12 Måling af Succes", group: "Process" },
  { id: "divider-13", file: "26-divider.html", isDivider: true },
  { id: "summary", file: "27-summary.html", navLabel: "13 Afrunding", group: "Closing" },
];
