export const pages = [
  { id: "heading", file: "01-heading.html", navLabel: "Forside", group: "Getting Started" },
  { id: "divider-1", file: "02-divider.html", isDivider: true },
  { id: "introduction", file: "03-introduction.html", navLabel: "Indledning", group: "Getting Started" },
  { id: "divider-2", file: "04-divider.html", isDivider: true },
  { id: "overview", file: "05-overview.html", navLabel: "Overblik", group: "Getting Started" },
  { id: "divider-3", file: "06-divider.html", isDivider: true },
  { id: "content-where", file: "07-content-where.html", navLabel: "Indhold & Platforme", group: "Getting Started" },
  { id: "divider-4", file: "08-divider.html", isDivider: true },
  { id: "audiences", file: "09-audiences.html", navLabel: "Målgrupper", group: "Getting Started" },
  { id: "divider-5", file: "10-divider.html", isDivider: true },
  { id: "styleguide", file: "11-styleguide.html", navLabel: "Visuel Identitet", group: "Brand" },
  { id: "divider-6", file: "12-divider.html", isDivider: true },
  { id: "facebook", file: "13-facebook-guidelines.html", navLabel: "Facebook", group: "Platform Guidelines" },
  { id: "divider-7", file: "14-divider.html", isDivider: true },
  { id: "instagram", file: "15-instagram-guidelines.html", navLabel: "Instagram", group: "Platform Guidelines" },
  { id: "divider-8", file: "16-divider.html", isDivider: true },
  { id: "linkedin", file: "17-linkedin-guidelines.html", navLabel: "LinkedIn", group: "Platform Guidelines" },
  { id: "divider-9", file: "18-divider.html", isDivider: true },
  { id: "tiktok", file: "19-tiktok-guidelines.html", navLabel: "TikTok", group: "Platform Guidelines" },
  { id: "divider-10", file: "20-divider.html", isDivider: true },
  { id: "catalogue", file: "21-catalogue-guidelines.html", navLabel: "Tone of Voice", group: "Process" },
  { id: "divider-11", file: "22-divider.html", isDivider: true },
  { id: "content-calendar", file: "23-content-calendar.html", navLabel: "Indholdskalender", group: "Process" },
  { id: "divider-12", file: "24-divider.html", isDivider: true },
  { id: "kpi", file: "25-kpi.html", navLabel: "KPI'er", group: "Process" },
  { id: "divider-13", file: "26-divider.html", isDivider: true },
  { id: "summary", file: "27-summary.html", navLabel: "Kreditering", group: "Closing" },
];
